---
- hosts: play
  remote_user: root
  tasks:
  - name: install Git
    apt: 
        pkg=git
        state=latest
  - name: Create .ssh directory 
    file:
        # The ansible_ssh_user is specified in the hosts file
        path=/.ssh/
        state=directory
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}
  - name: Install known_hosts file
    copy: 
        src=known_hosts
        dest=/.ssh/known_hosts
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}  
  - name: Clone Playpen
    git: 
        repo=https://github.com/thestinger/playpen.git
        dest=/home/{{ ansible_ssh_user }}/playpen_source
  - name: Install prerequisite packages for building playpen
    apt:
        pkg={{ item }}
        state=present
    with_items:
        - make
        - pkg-config
        - clang
        - gio-20
        - libglib2.0-dev
        - gcc
  - name: Make Install Playpen
    command: make install
        chdir=/home/{{ansible_ssh_user }}/playpen_source/
        # creates= TODO
