---
- hosts: play
  remote_user: root
  tasks:
  - name: install Git
    apt: 
        pkg=git
        state=latest
  - name: Create .ssh directory 
    file:
        path=/home/{{ ansible_ssh_user }}/.ssh/
        state=directory
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}
  - name: Install known_hosts file
    copy: 
        src=known_hosts
        dest=/home/{{ ansible_ssh_user }}/.ssh/known_hosts
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}
