---
- name: apt-get update
  apt:
      update_cache=yes
- name: Install prerequisite packages
  apt:
      pkg={{ item }}
      state=present
  with_items: 
      - python
      - python-pip
      - python-dev
      - python-setuptools
      - stunnel
      # we need Git later and Ansible doesn't auto-install it
      - git
- name: install Buildbot
  easy_install:
      name: buildbot==0.8.12
- name: Create buildbot user
  user:
      name: "buildbot"
      home: "/home/buildbot"
      shell: /bin/bash
      createhome: yes  
- name: Clone my fork of the Buildbot configs
  git: 
      repo='https://github.com/edunham/rust-buildbot.git'
      dest='/home/buildbot/rust-buildbot'

- name: Try to apply the patches from the configs
  patch:
        src=/home/buildbot/rust-buildbot/master/{{ item.patch }}.patch
        basedir={{ item.base }}
  with_items: 
    - { patch: 'ec2buildslave-take-subnet_id', base: '/usr/local/lib/' }
    - { patch: 'buildbot', base: '/usr/local/lib' }
    - { patch: 'prune-changes-in-batches-of-100', base: '/usr/local/lib' }

- name: Start Buildbot
  command: buildbot start master
  args:
      chdir: /home/buildbot/rust-buildbot/master
